services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    depends_on: [db]
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s /home/node/.docker/frontend/entrypoint.sh
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./frontend:/home/node/app
      - ./.docker:/home/node/.docker
  db:
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pokemontcg
      POSTGRES_DB: pokemon-tcg
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
